In [2]:
import pandas as pd
import numpy as np
import os
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler, OneHotEncoder, Normalizer
import matplotlib.pyplot as plt
os.chdir('C:\\Users\\Manoj\\Desktop\\Edureka_Python')

In [3]:
data = pd.read_csv("run_or_walk.csv")
data.head()

date                time username  wrist  activity  acceleration_x  \
0  2017-6-30  13:51:15:847724020   viktor      0         0          0.2650   
1  2017-6-30  13:51:16:246945023   viktor      0         0          0.6722   
2  2017-6-30  13:51:16:446233987   viktor      0         0          0.4399   
3  2017-6-30  13:51:16:646117985   viktor      0         0          0.3031   
4  2017-6-30  13:51:16:846738994   viktor      0         0          0.4814   

   acceleration_y  acceleration_z  gyro_x  gyro_y  gyro_z  
0         -0.7814         -0.0076 -0.0590  0.0325 -2.9296  
1         -1.1233         -0.2344 -0.1757  0.0208  0.1269  
2         -1.4817          0.0722 -0.9105  0.1063 -2.4367  
3         -0.8125          0.0888  0.1199 -0.4099 -2.9336  
4         -0.9312          0.0359  0.0527  0.4379  2.4922

In [8]:
data.username.unique()

array(['viktor'], dtype=object)

In [5]:
from sklearn.naive_bayes import GaussianNB
classifier_nb = GaussianNB()

In [6]:
from sklearn.model_selection import train_test_split

In [10]:
x = data.iloc[:,5:].values
x

array([[ 0.265 , -0.7814, -0.0076, -0.059 ,  0.0325, -2.9296],
       [ 0.6722, -1.1233, -0.2344, -0.1757,  0.0208,  0.1269],
       [ 0.4399, -1.4817,  0.0722, -0.9105,  0.1063, -2.4367],
       ...,
       [ 0.4587, -1.178 , -0.2827, -1.45  , -0.2792, -1.2616],
       [ 0.259 , -0.8582, -0.0759, -1.5165,  0.456 , -1.7755],
       [ 0.314 , -0.8008, -0.0911,  0.1183,  1.085 ,  1.2814]])

In [11]:
y = data.iloc[:,4].values
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [12]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x = sc_x.fit_transform(x)

In [13]:
x

array([[ 0.33668266, -0.33231618,  0.6293112 , -0.05039065, -0.00392358,
        -1.5419494 ],
       [ 0.74013342, -0.85156246,  0.16342314, -0.14349622, -0.013684  ,
         0.05462392],
       [ 0.50997229, -1.39586742,  0.79323478, -0.72973418,  0.05764218,
        -1.28448139],
       ...,
       [ 0.52859919, -0.93463579,  0.06420624, -1.16015794, -0.26395131,
        -0.67066385],
       [ 0.3307379 , -0.44895295,  0.4890107 , -1.21321296,  0.34937044,
        -0.93910129],
       [ 0.3852315 , -0.36177911,  0.45778716,  0.09106279,  0.87409756,
         0.65768097]])

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [15]:
classifier_nb.fit(x_train,y_train)
y_pred = classifier_nb.predict(x_test)
confusion_matrix(y_test, y_pred)

array([[8727,   93],
       [ 706, 8192]], dtype=int64)

In [16]:
(8727+8192)/(8727+93+706+8192)

0.9549046167739023

In [17]:
from sklearn.metrics import classification_report

In [19]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.99      0.96      8820
           1       0.99      0.92      0.95      8898

   micro avg       0.95      0.95      0.95     17718
   macro avg       0.96      0.96      0.95     17718
weighted avg       0.96      0.95      0.95     17718



In [20]:
data.head()

date                time username  wrist  activity  acceleration_x  \
0  2017-6-30  13:51:15:847724020   viktor      0         0          0.2650   
1  2017-6-30  13:51:16:246945023   viktor      0         0          0.6722   
2  2017-6-30  13:51:16:446233987   viktor      0         0          0.4399   
3  2017-6-30  13:51:16:646117985   viktor      0         0          0.3031   
4  2017-6-30  13:51:16:846738994   viktor      0         0          0.4814   

   acceleration_y  acceleration_z  gyro_x  gyro_y  gyro_z  
0         -0.7814         -0.0076 -0.0590  0.0325 -2.9296  
1         -1.1233         -0.2344 -0.1757  0.0208  0.1269  
2         -1.4817          0.0722 -0.9105  0.1063 -2.4367  
3         -0.8125          0.0888  0.1199 -0.4099 -2.9336  
4         -0.9312          0.0359  0.0527  0.4379  2.4922

In [24]:
x_acc = data.iloc[:,5:8].values
x_acc
sc_x = StandardScaler()
x_acc= sc_x.fit_transform(x_acc)

In [25]:
x_gyr = data.iloc[:,8:].values
x_gyr
sc_x = StandardScaler()
x_gyr= sc_x.fit_transform(x_gyr)

In [27]:
x_train, x_test, y_train, y_test = train_test_split(x_acc,y,test_size=0.2)
classifier_nb.fit(x_train,y_train)
y_pred = classifier_nb.predict(x_test)
print("Acceleration Predictors :" ,confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

#0.9570493283666328

Acceleration Predictors : [[8841   61]
 [ 700 8116]]
              precision    recall  f1-score   support

           0       0.93      0.99      0.96      8902
           1       0.99      0.92      0.96      8816

   micro avg       0.96      0.96      0.96     17718
   macro avg       0.96      0.96      0.96     17718
weighted avg       0.96      0.96      0.96     17718



In [28]:
x_train, x_test, y_train, y_test = train_test_split(x_gyr,y,test_size=0.2)
classifier_nb.fit(x_train,y_train)
y_pred = classifier_nb.predict(x_test)
print("Gyro Predictors :",confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

#0.6479286601196523

Gyro Predictors : [[6588 2180]
 [4058 4892]]
              precision    recall  f1-score   support

           0       0.62      0.75      0.68      8768
           1       0.69      0.55      0.61      8950

   micro avg       0.65      0.65      0.65     17718
   macro avg       0.66      0.65      0.64     17718
weighted avg       0.66      0.65      0.64     17718



In [29]:
(8841+8116)/(8841 +  61+ 700+ 8116)

0.9570493283666328

In [30]:
(6588+4892)/(6588+ 2180+4058 +4892)

0.6479286601196523