In [5]:
import pandas as pd
import numpy as np
import os
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler, OneHotEncoder, Normalizer
import matplotlib.pyplot as plt
os.chdir('C:\\Users\\Manoj\\Desktop\\Edureka_Python')

In [6]:
data = pd.read_csv("bio-degradabale-data.csv", delimiter = ';')
data.head()

3.919  2.6909  0  0.1  0.2  0.3  0.4  31.4  2  0.5 ...  0.19  0.20  0.21  \
0  4.170  2.1144  0    0    0    0    0  30.8  1    1 ...     0     0     0   
1  3.932  3.2512  0    0    0    0    0  26.7  2    4 ...     0     0     1   
2  3.000  2.7098  0    0    0    0    0  20.0  0    2 ...     0     0     1   
3  4.236  3.3944  0    0    0    0    0  29.4  2    4 ...     0     0     0   
4  4.236  3.4286  0    0    0    0    0  28.6  2    4 ...     0     0     0   

   2.949  1.591  0.22  7.253  0.23  0.24  RB  
0  3.315  1.967     0  7.257     0     0  RB  
1  3.076  2.417     0  7.601     0     0  RB  
2  3.046  5.000     0  6.690     0     0  RB  
3  3.351  2.405     0  8.003     0     0  RB  
4  3.351  2.556     0  7.904     0     0  RB  

[5 rows x 42 columns]

In [7]:
x = data.iloc[:,0:41].values
x

array([[ 4.17  ,  2.1144,  0.    , ...,  7.257 ,  0.    ,  0.    ],
       [ 3.932 ,  3.2512,  0.    , ...,  7.601 ,  0.    ,  0.    ],
       [ 3.    ,  2.7098,  0.    , ...,  6.69  ,  0.    ,  0.    ],
       ...,
       [ 4.869 ,  1.767 ,  0.    , ...,  9.537 ,  1.    ,  0.    ],
       [ 5.158 ,  1.6914,  2.    , ..., 11.055 ,  0.    ,  1.    ],
       [ 5.076 ,  2.6588,  2.    , ...,  9.13  ,  0.    ,  2.    ]])

In [8]:
data['RB'] = data['RB'].astype('category')
data['RB'] = data['RB'].cat.codes


y = data.iloc[:,41].values
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int8)

In [9]:
sc = StandardScaler()
x = sc.fit_transform(x)
x

array([[-1.12300743, -1.14946675, -0.49051132, ..., -1.10677535,
        -0.16062326, -0.32329263],
       [-1.55869104,  0.21815121, -0.49051132, ..., -0.82963799,
        -0.16062326, -0.32329263],
       [-3.26481338, -0.43317564, -0.49051132, ..., -1.56356861,
        -0.16062326, -0.32329263],
       ...,
       [ 0.15658432, -1.56740349, -0.49051132, ...,  0.73006526,
         2.97450473, -0.32329263],
       [ 0.6856287 , -1.65835345,  0.87721071, ...,  1.9530144 ,
        -0.16062326,  0.12330034],
       [ 0.53551922, -0.49453078,  0.87721071, ...,  0.4021731 ,
        -0.16062326,  0.56989331]])

In [10]:
x_train,x_test, y_train,y_test = train_test_split(x,y, test_size = 0.2)

In [11]:
from xgboost import XGBClassifier

In [12]:
xg = XGBClassifier()

In [13]:
xg.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, learning_rate=0.1,
       max_delta_step=0, max_depth=3, min_child_weight=1, missing=None,
       n_estimators=100, n_jobs=1, nthread=None,
       objective='binary:logistic', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
       subsample=1, verbosity=1)

In [14]:
y_pred_xg = xg.predict(x_test)

In [15]:
confusion_matrix(y_test,y_pred_xg)

array([[133,  20],
       [ 16,  42]], dtype=int64)

In [16]:
(133+42)/(133+20+16+42)

0.8293838862559242

In [17]:
from sklearn.tree import DecisionTreeClassifier

In [23]:
dt = DecisionTreeClassifier(criterion = 'entropy')

In [24]:
dt.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [25]:
y_pred_dt = dt.predict(x_test)

In [26]:
confusion_matrix(y_test, y_pred_dt)

array([[120,  33],
       [ 18,  40]], dtype=int64)

In [28]:
print((123+41)/(123+30+17+41))

print((120+40)/(120+  33+  18+  40))

0.7772511848341233
0.7582938388625592


In [29]:
from sklearn.ensemble import AdaBoostClassifier

In [30]:
ad = AdaBoostClassifier()

In [31]:
ad.fit(x_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [32]:
y_pred_ad = ad.predict(x_test)

In [33]:
confusion_matrix(y_test,y_pred_ad)

array([[129,  24],
       [ 13,  45]], dtype=int64)

In [34]:
(129+45)/(129+24+13+45)

0.8246445497630331

In [40]:
pc = PCA(n_components=6)

In [41]:
x_pc = pc.fit_transform(x)

In [42]:
pc.explained_variance_ratio_

array([0.18031265, 0.12271404, 0.11117129, 0.08301228, 0.06066559,
       0.05696556])

In [43]:
x_pc.shape

(1054, 6)

In [44]:
x_train,x_test, y_train,y_test = train_test_split(x_pc,y, test_size = 0.2)


In [45]:
xg.fit(x_train,y_train)
y_pred_pc_xg = xg.predict(x_test)
confusion_matrix(y_test,y_pred_pc_xg)

array([[122,  15],
       [ 24,  50]], dtype=int64)

In [48]:
172/211

0.8151658767772512

In [49]:
ad.fit(x_train,y_train)
y_pred_pc_ad = ad.predict(x_test)
confusion_matrix(y_test,y_pred_pc_ad)

array([[117,  20],
       [ 23,  51]], dtype=int64)

In [52]:
168/211

0.7962085308056872

In [53]:
no = Normalizer()
x_no = no.fit_transform(x)

In [54]:
x_train,x_test, y_train,y_test = train_test_split(x_no,y, test_size = 0.2)

In [55]:
xg.fit(x_train,y_train)
y_pred_pc_xg = xg.predict(x_test)
confusion_matrix(y_test,y_pred_pc_xg)
#85.78

array([[130,  13],
       [ 17,  51]], dtype=int64)

In [56]:
ad.fit(x_train,y_train)
y_pred_pc_ad = ad.predict(x_test)
confusion_matrix(y_test,y_pred_pc_ad)
#87.2

array([[129,  14],
       [ 13,  55]], dtype=int64)

# Adaboost with normalization giving 87.2 accuracy.